[project]
name = 'sturdy_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.pod_with_payment_for_update]
path = 'contracts/pod_with_payment_for_update.clar'
clarity_version = 2
epoch = 2.5

[contracts.random_winner_selection]
path = 'contracts/random_winner_selection.clar'
clarity_version = 2
epoch = 2.5

[contracts.research_funding]
path = 'contracts/research_funding.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_contract_factory]
path = 'contracts/storage_contract_factory.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
